<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.0.0',
  'acceptable_sugar_versions' =>
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' =>
  array (
    0 => 'ENT',
    1 => 'ULT',
  ),
  'readme' => '',
  'key' => 'raw',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Editable list dashlet',
  'published_date' => '2016-03-25 012:43:07',
  'type' => 'module',
  'version' => 1450342448,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'copy' =>
  array (
    0 =>
    array (
      'from' => '<basepath>/custom/clients/base/views/editable_list_dashlet/editable_list_dashlet.php',
      'to' => 'custom/clients/base/views/editable_list_dashlet/editable_list_dashlet.php',
    ),
  1 =>
    array (
      'from' => '<basepath>/custom/clients/base/views/editable_list_dashlet/row.hbs',
      'to' => 'custom/clients/base/views/editable_list_dashlet/row.hbs',
    ),
  2 =>
    array (
      'from' => '<basepath>/custom/clients/base/views/editable_list_dashlet/editable_list_dashlet.js',
      'to' => 'custom/clients/base/views/editable_list_dashlet/editable_list_dashlet.js',
    ),
  3 =>
    array (
      'from' => '<basepath>/custom/clients/base/views/editable_list_dashlet/editable_list_dashlet.hbs',
      'to' => 'custom/clients/base/views/editable_list_dashlet/editable_list_dashlet.hbs',
    ),
  ),
);

